### ISSUE TITLE
Incorrect Report Model

### ISSUE THREAD

**Issue by connory3** [vivianbuan/cs3240-s15-team20#4]
The report model currently has a text field for the author. It is my understanding that author is supposed to be associated with a user (use the UserProfile model from accounts). Even if we keep the author field, we need a field to link it to a User for internal purposes.

**Comment by revanthkolli** [comment]
Yeah thats the thing i was talking about in the group me. This is just a temp thing, the author field is gonna be fixed (uneditable) and automatically set to the current users name/id.
