### ISSUE TITLE
cannot add report

### ISSUE THREAD

**Issue by yb2fj** [vivianbuan/cs3240-s15-team20#5]
After I pulled few minutes I cannot add reports to our website,

**Comment by vivianbuan** [comment]
What's the error message?

**Comment by yb2fj** [comment]
OperationalError at /reports/add_report/

no such column: Report_folder.owner_id

Request Method:GETRequest URL:http://127.0.0.1:8000/reports/add_report/Django
Version:1.7.5Exception Type:OperationalErrorException Value:

no such column: Report_folder.owner_id

Exception Location:C:\Python34\lib\site-packages\django\db\backends\sqlite3\base.py
in execute, line 485Python Executable:C:\Python34\python.exePython Version:
3.4.2Python Path:

['C:\Users\yb2fj\cs3240-s15-team20\SecureWitness',
 'C:\Python34\lib\site-packages\setuptools-12.0.5-py3.4.egg',
 'C:\Python34\python34.zip',
 'C:\Python34\DLLs',
 'C:\Python34\lib',
 'C:\Python34',
 'C:\Python34\lib\site-packages']

Server time:

_Wed, 15 Apr 2015 14:27:48 -0400even after migration._

**Comment by vivianbuan** [comment]
Did you do makemigrations? I edit the folder model so that may be the issue
because you haven't update your database.

**Comment by yb2fj** [comment]
I did make migration and migrate. I will try to delete my database and
recreate it

**Comment by vivianbuan** [comment]
Or you can do syncdb.

**Comment by revanthkolli** [comment]
I'm getting an error when I do migrate: django.db.utils.IntegrityError: 
NOT NULL constraint failed: Report_folder__new.owner_id

**Comment by yb2fj** [comment]
I flushed all the data and recreated; now it's working.

**Comment by yb2fj** [comment]
just do
python manage.py flush
then manage.py syncdb
